# Slices
- Python
    - list, tuple
    - str
- Numpy
    - ndarray
- Pandas:
    - DataFrame

In [39]:
import numpy as np
# https://numpy.org/doc/stable/reference/index.html#reference

## slices on str

In [1]:
text = 'Toulouse, ville rose'

In [2]:
# from index 10 (included) to 15 (excluded)
text[10:15]

'ville'

In [3]:
text[15:]

' rose'

In [4]:
text[:10]

'Toulouse, '

In [5]:
text[:]

'Toulouse, ville rose'

In [6]:
text[-4:]

'rose'

In [7]:
text[-4:-2]

'ro'

In [8]:
text[-2:-4]

''

In [9]:
text[-3:-5:-1]

'or'

In [10]:
text[::-1]

'esor elliv ,esuoluoT'

In [11]:
text[::2]

'Tuos,vlers'

In [12]:
text[1::2]

'olue il oe'

In [13]:
text[5:10_000]

'use, ville rose'

In [14]:
# TypeError: 'str' object does not support item assignment
# text[:2] = '##'

## slices on list

In [15]:
cities = ['Toulouse', 'Pau', 'Bayonne', 'Strasbourg', 'Montpellier', 'Marseille']

In [16]:
cities[:3]

['Toulouse', 'Pau', 'Bayonne']

In [17]:
cities[:3] = ['Paris', 'Bordeaux']
cities

['Paris', 'Bordeaux', 'Strasbourg', 'Montpellier', 'Marseille']

In [18]:
cities[:2] = []
cities

['Strasbourg', 'Montpellier', 'Marseille']

In [19]:
# methods: cities.remove/pop/insert/append/extend/....

In [20]:
del cities[:2]
cities

['Marseille']

In [21]:
n = len(cities)
cities[n:] = ['Paris', 'Bordeaux', 'Strasbourg', 'Montpellier']
cities

['Marseille', 'Paris', 'Bordeaux', 'Strasbourg', 'Montpellier']

In [23]:
index = 1
cities[index:index] = ['Pau', 'Bayonne', 'Toulouse']
cities

['Marseille',
 'Pau',
 'Bayonne',
 'Toulouse',
 'Paris',
 'Bordeaux',
 'Strasbourg',
 'Montpellier']

In [28]:
[ m for m in dir(cities) if m in ['__delitem__', '__getitem__', '__setitem__'] ]

['__delitem__', '__getitem__', '__setitem__']

In [29]:
[ m for m in dir(str) if m in ['__delitem__', '__getitem__', '__setitem__'] ]

['__getitem__']

In [30]:
[ m for m in dir(tuple) if m in ['__delitem__', '__getitem__', '__setitem__'] ]

['__getitem__']

In [31]:
square_ok_12 =  [ 
    [138,	8,	17,	127,	114,	32,	41,	103,	90,	56,	65,	79],
    [19,	125,	140,	6,	43,	101,	116,	30,	67,	77,	92,	54],
    [128,	18,	7,	137,	104,	42,	31,	113,	80,	66,	55,	89],
    [5,	139,	126,	20,	29,	115,	102,	44,	53,	91,	78,	68],
    [136,	10,	15,	129,	112,	34,	39,	105,	88,	58,	63,	81],
    [21,	123,	142,	4,	45,	99,	118,	28,	69,	75,	94,	52],
    [130,	16,	9,	135,	106,	40,	33,	111,	82,	64,	57,	87],
    [3,	141,	124,	22,	27,	117,	100,	46,	51,	93,	76,	70],
    [134,	12,	13,	131,	110,	36,	37,	107,	86,	60,	61,	83],
    [23,	121,	144,	2,	47,	97,	120,	26,	71,	73,	96,	50],
    [132,	14,	11,	133,	108,	38,	35,	109,	84,	62,	59,	85],
    [1,	143,	122,	24,	25,	119,	98,	48,	49,	95,	74,	72]
]

In [37]:
# type list does not accept tuple of slices (n dimension)
# square_ok_12[:3, :3]  # TypeError: list indices must be integers or slices, not tuple
[ row[:3]  for row in square_ok_12[:3] ]

[[138, 8, 17], [19, 125, 140], [128, 18, 7]]

## slices on ndarray (numpy)

In [40]:
square12 = np.array(square_ok_12)
square12

array([[138,   8,  17, 127, 114,  32,  41, 103,  90,  56,  65,  79],
       [ 19, 125, 140,   6,  43, 101, 116,  30,  67,  77,  92,  54],
       [128,  18,   7, 137, 104,  42,  31, 113,  80,  66,  55,  89],
       [  5, 139, 126,  20,  29, 115, 102,  44,  53,  91,  78,  68],
       [136,  10,  15, 129, 112,  34,  39, 105,  88,  58,  63,  81],
       [ 21, 123, 142,   4,  45,  99, 118,  28,  69,  75,  94,  52],
       [130,  16,   9, 135, 106,  40,  33, 111,  82,  64,  57,  87],
       [  3, 141, 124,  22,  27, 117, 100,  46,  51,  93,  76,  70],
       [134,  12,  13, 131, 110,  36,  37, 107,  86,  60,  61,  83],
       [ 23, 121, 144,   2,  47,  97, 120,  26,  71,  73,  96,  50],
       [132,  14,  11, 133, 108,  38,  35, 109,  84,  62,  59,  85],
       [  1, 143, 122,  24,  25, 119,  98,  48,  49,  95,  74,  72]])

In [41]:
square12.shape

(12, 12)

In [42]:
square12.dtype

dtype('int32')

In [43]:
square12.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False

In [44]:
extract = square12[:3, :3]
extract

array([[138,   8,  17],
       [ 19, 125, 140],
       [128,  18,   7]])

In [45]:
extract.flags

  C_CONTIGUOUS : False
  F_CONTIGUOUS : False
  OWNDATA : False
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False

In [46]:
extract[0, 0] = 137
assert extract[0, 0] == 137
assert square12[0, 0] == 137

In [47]:
n,_ = square12.shape
n

12

In [50]:
# slice : column of index numColumn
numColumn = 6
square12[:, numColumn ]

array([ 41, 116,  31, 102,  39, 118,  33, 100,  37, 120,  35,  98])

In [ ]:
# 2 diags